### ISSUE TITLE
Make search better

### ISSUE THREAD

**Issue by Lvl4Sword** [CryptocurrencyExplorer/CryptocurrencyExplorer#41]
``ilike`` and ``like`` don't search on index, which makes the SQL query **incredibly slow**. I'm glad that there's search, but it needs to be a lot faster.

**Comment by dermoth** [comment]
Indeed - indexes uses hashes to index the data - you can hash a value and find the index position, but you can't hash a partial value as with a like query.

IIRC postgresql has a fulltext index which can be used to implement the kind of searches you like. Also some indexing functions end up having the data in sorted order, so if you know the beginning of a value you may be able to select a range and search on it (I think that would work on InnoDB, not sure about PostgreSQL...). Otherwise there are tools better suited for the job like elasticsearch...

**Comment by Lvl4Sword** [comment]
A PR with elasticsearch would be great. I feel like elasticsearch is probably the best step forward.

**Comment by Lvl4Sword** [comment]
The current search; at least for Woodcoin, is fairly fast.
When searching `7ed468`, the search results page shows up pretty quickly. This search currently provides 11 blocks and 8 transactions in about 2~ seconds on average, which is pretty good to me.

While I'd love to see it faster, I think this is about as good as it's going to get without redoing search entirely.
There's only so much I think that can be done when you're searching using `ilike` or `like` queries.

If you ( the reader ) would like to redo searching or feel like the current setup is incorrect and/or can easily be optimized further, feel free to comment.

Closing this for now.
